const $=s=>document.querySelector(s), fmt=n=>new Intl.NumberFormat('id-ID').format(Math.round(Number(n)||0)), money=n=>'Rp '+fmt(n);
const today=()=>new Date().toISOString().slice(0,10), uid=p=>p+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);
const DBKEY='miniERPProduksi_v1';
const seed={
  products:[
    {id:'FG001',name:'Samosa Ayam',unit:'pcs',priceRegular:3500,priceReseller:2800,hpp:1850,minStock:20},
    {id:'FG002',name:'Samosa Keju',unit:'pcs',priceRegular:4000,priceReseller:3200,hpp:2100,minStock:20}
  ],
  materials:[
    {id:'RM001',name:'Daging Ayam',unit:'gram',stock:0,avgCost:0,minStock:2000},
    {id:'RM002',name:'Kulit Samosa',unit:'pcs',stock:0,avgCost:0,minStock:100}
  ],
  packaging:[
    {id:'PK001',name:'Plastik Inner',type:'INNER',unit:'pcs',stock:0,avgCost:0,minStock:100},
    {id:'PK002',name:'Master Carton',type:'OUTER',unit:'pcs',stock:0,avgCost:0,minStock:10}
  ],
  fgStock:{FG001:0,FG002:0}, orders:[], materialTx:[], packagingTx:[], productions:[]
};
let db=load();
function load(){try{return Object.assign(structuredClone(seed),JSON.parse(localStorage.getItem(DBKEY)||'{}'))}catch(e){return structuredClone(seed)}}
function save(){localStorage.setItem(DBKEY,JSON.stringify(db));render(active)}
const pages=[['dashboard','Dashboard'],['order','Order'],['material','Raw Material'],['packaging','Packaging'],['production','Produksi'],['stock','Stok'],['reports','Laporan'],['settings','Master']];
let active='dashboard';
function nav(id){active=id;document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));render(id);scrollTo(0,0)}
function buildNav(){ $('#tabs').innerHTML=pages.map(([id,n])=>`<button data-nav="${id}" onclick="nav('${id}')">${n}</button>`).join(''); $('#bottomnav').innerHTML=[['dashboard','Home'],['order','Order'],['production','Produksi'],['stock','Stok'],['reports','Laporan']].map(([id,n])=>`<button data-nav="${id}" onclick="nav('${id}')">${n}</button>`).join('');}
function orderTotals(o){const subtotal=o.items.reduce((s,i)=>s+i.qty*i.price,0);const hpp=o.items.reduce((s,i)=>s+i.qty*i.hpp,0);return{subtotal,hpp,profit:subtotal-hpp}}
function openOrders(){return db.orders.filter(o=>o.status!=='SELESAI'&&o.status!=='BATAL')}
function outstandingByProduct(){const r={};db.products.forEach(p=>r[p.id]={product:p,orderQty:0,stock:Number(db.fgStock[p.id]||0),need:0});openOrders().forEach(o=>o.items.forEach(i=>{if(r[i.productId])r[i.productId].orderQty+=Number(i.qty)}));Object.values(r).forEach(x=>x.need=Math.max(0,x.orderQty-x.stock));return Object.values(r)}
function render(id){document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));({dashboard:renderDashboard,order:renderOrder,material:renderMaterial,packaging:renderPackaging,production:renderProduction,stock:renderStock,reports:renderReports,settings:renderSettings}[id]||(()=>{}))()}
function renderDashboard(){const sales=db.orders.filter(o=>o.status==='SELESAI').reduce((s,o)=>s+orderTotals(o).subtotal,0),profit=db.orders.filter(o=>o.status==='SELESAI').reduce((s,o)=>s+orderTotals(o).profit,0),need=outstandingByProduct().filter(x=>x.need>0),lowRM=db.materials.filter(x=>x.stock<=x.minStock).length,lowPK=db.packaging.filter(x=>x.stock<=x.minStock).length;$('#dashboard').innerHTML=`
<div class="grid3"><div class="kpi"><b>${openOrders().length}</b><span>Order aktif</span></div><div class="kpi"><b>${need.length}</b><span>Produk perlu produksi</span></div><div class="kpi"><b>${lowRM+lowPK}</b><span>Item stok kritis</span></div><div class="kpi"><b>${money(sales)}</b><span>Total penjualan selesai</span></div><div class="kpi"><b>${money(profit)}</b><span>Total profit kotor</span></div><div class="kpi"><b>${db.productions.reduce((s,x)=>s+Number(x.qty),0)}</b><span>Total hasil produksi</span></div></div>
<div class="card"><h2>Outstanding Produksi</h2><table><thead><tr><th>Produk</th><th class="num">Order Aktif</th><th class="num">Stok FG</th><th class="num">Perlu Produksi</th></tr></thead><tbody>${outstandingByProduct().map(x=>`<tr><td>${x.product.name}</td><td class="num">${fmt(x.orderQty)}</td><td class="num">${fmt(x.stock)}</td><td class="num"><b>${fmt(x.need)}</b></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Belum ada data</td></tr>'}</tbody></table></div>`}
function renderOrder(){const prodOpts=db.products.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');$('#order').innerHTML=`
<div class="card no-print"><h2>Input Order</h2><div class="row"><div><label>Tanggal</label><input id="oDate" type="date" value="${today()}"></div><div><label>Jenis Order</label><select id="oType" onchange="syncOrderPrice()"><option>REGULER</option><option>RESELLER</option></select></div><div><label>Nama Pelanggan</label><input id="oCustomer" placeholder="Nama pelanggan"></div><div><label>Produk</label><select id="oProduct" onchange="syncOrderPrice()">${prodOpts}</select></div><div><label>Qty</label><input id="oQty" type="number" min="1" value="1"></div><div><label>Harga</label><input id="oPrice" type="number"></div></div><div class="actions"><button class="btn" onclick="addOrder()">Simpan Order</button></div></div>
<div class="card"><h2>Rekap Order</h2><table><thead><tr><th>No</th><th>Pelanggan</th><th>Jenis</th><th>Item</th><th class="num">Total</th><th>Status</th><th class="no-print">Aksi</th></tr></thead><tbody>${db.orders.slice().reverse().map(o=>{let t=orderTotals(o);return`<tr><td>${o.no}<div class="small">${o.date}</div></td><td>${o.customer}</td><td><span class="badge ${o.type==='RESELLER'?'res':'reg'}">${o.type}</span></td><td>${o.items.map(i=>`${i.name} × ${fmt(i.qty)}`).join('<br>')}</td><td class="num">${money(t.subtotal)}</td><td><span class="badge ${o.status==='SELESAI'?'ok':''}">${o.status}</span></td><td class="no-print"><button class="btn secondary" onclick="printReceipt('${o.id}')">Struk</button> ${o.status!=='SELESAI'?`<button class="btn ok" onclick="finishOrder('${o.id}')">Selesai</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Belum ada order</td></tr>'}</tbody></table></div>`;setTimeout(syncOrderPrice,0)}
window.syncOrderPrice=()=>{let p=db.products.find(x=>x.id===$('#oProduct')?.value);if(p&&$('#oPrice'))$('#oPrice').value=$('#oType').value==='RESELLER'?p.priceReseller:p.priceRegular}
window.addOrder=()=>{let p=db.products.find(x=>x.id===$('#oProduct').value),qty=Number($('#oQty').value),price=Number($('#oPrice').value),customer=$('#oCustomer').value.trim();if(!p||qty<=0||!customer)return alert('Lengkapi pelanggan, produk, dan qty.');let no='SO-'+new Date().toISOString().replace(/\D/g,'').slice(2,12);db.orders.push({id:uid('O'),no,date:$('#oDate').value,type:$('#oType').value,customer,status:'BARU',items:[{productId:p.id,name:p.name,qty,price,hpp:p.hpp}]});save()}
window.finishOrder=id=>{let o=db.orders.find(x=>x.id===id);if(!o)return;for(const i of o.items){let st=Number(db.fgStock[i.productId]||0);if(st<i.qty)return alert(`Stok ${i.name} tidak cukup. Stok ${fmt(st)}, order ${fmt(i.qty)}.`)}o.items.forEach(i=>db.fgStock[i.productId]-=Number(i.qty));o.status='SELESAI';o.completedAt=new Date().toISOString();save()}
window.printReceipt=id=>{let o=db.orders.find(x=>x.id===id),t=orderTotals(o);let w=window.open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Struk ${o.no}</title><style>body{font-family:monospace;max-width:320px;margin:auto;padding:16px}h2{text-align:center}table{width:100%;border-collapse:collapse}td{padding:4px 0}.r{text-align:right}.line{border-top:1px dashed #000;margin:8px 0}</style></head><body><h2>STRUK ORDER</h2><div>No: ${o.no}</div><div>Tanggal: ${o.date}</div><div>Pelanggan: ${o.customer}</div><div>Jenis: ${o.type}</div><div class="line"></div><table>${o.items.map(i=>`<tr><td>${i.name}<br>${fmt(i.qty)} x ${money(i.price)}</td><td class="r">${money(i.qty*i.price)}</td></tr>`).join('')}</table><div class="line"></div><b>Total <span style="float:right">${money(t.subtotal)}</span></b><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function txForm(kind){let isRM=kind==='material',arr=isRM?db.materials:db.packaging,opts=arr.map(x=>`<option value="${x.id}">${x.name}${isRM?'':' - '+x.type}</option>`).join('');return`<div class="card no-print"><h2>${isRM?'Transaksi Raw Material':'Transaksi Packaging'}</h2><div class="row3"><div><label>Tanggal</label><input id="${kind}Date" type="date" value="${today()}"></div><div><label>Jenis Transaksi</label><select id="${kind}Mode"><option value="IN">PEMBELIAN / MASUK</option><option value="OUT">PEMAKAIAN / KELUAR</option></select></div><div><label>Item</label><select id="${kind}Item">${opts}</select></div><div><label>Qty</label><input id="${kind}Qty" type="number" min="0" step="0.01"></div><div><label>Harga/unit (untuk pembelian)</label><input id="${kind}Cost" type="number" min="0" step="0.01" value="0"></div><div><label>Keterangan</label><input id="${kind}Note" placeholder="Supplier / batch / catatan"></div></div><button class="btn" onclick="addTx('${kind}')">Simpan Transaksi</button></div>`}
window.addTx=kind=>{let isRM=kind==='material',arr=isRM?db.materials:db.packaging,txs=isRM?db.materialTx:db.packagingTx,item=arr.find(x=>x.id===$(`#${kind}Item`).value),mode=$(`#${kind}Mode`).value,qty=Number($(`#${kind}Qty`).value),cost=Number($(`#${kind}Cost`).value||0);if(!item||qty<=0)return alert('Qty harus lebih dari 0.');if(mode==='OUT'&&item.stock<qty)return alert('Stok tidak cukup.');if(mode==='IN'){let oldVal=item.stock*item.avgCost,newVal=qty*cost;item.stock+=qty;item.avgCost=item.stock?((oldVal+newVal)/item.stock):0}else item.stock-=qty;txs.push({id:uid('T'),date:$(`#${kind}Date`).value,itemId:item.id,itemName:item.name,mode,qty,cost,note:$(`#${kind}Note`).value});save()}
function renderMaterial(){ $('#material').innerHTML=txForm('material')+txTable(db.materialTx,'Raw Material') }
function renderPackaging(){ $('#packaging').innerHTML=txForm('packaging')+txTable(db.packagingTx,'Packaging') }
function txTable(txs,title){return`<div class="card"><h2>Rekap ${title}</h2><table><thead><tr><th>Tanggal</th><th>Item</th><th>Transaksi</th><th class="num">Qty</th><th class="num">Harga</th><th>Catatan</th></tr></thead><tbody>${txs.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${x.itemName}</td><td>${x.mode==='IN'?'MASUK':'PAKAI'}</td><td class="num">${fmt(x.qty)}</td><td class="num">${x.mode==='IN'?money(x.cost):'-'}</td><td>${x.note||'-'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Belum ada transaksi</td></tr>'}</tbody></table></div>`}
function renderProduction(){let opts=db.products.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');$('#production').innerHTML=`<div class="card no-print"><h2>Input Hasil Produksi</h2><div class="row"><div><label>Tanggal</label><input id="pDate" type="date" value="${today()}"></div><div><label>Produk</label><select id="pProduct">${opts}</select></div><div><label>Qty Good</label><input id="pQty" type="number" min="1"></div><div><label>Reject</label><input id="pReject" type="number" min="0" value="0"></div><div class="full"><label>Catatan / Batch</label><input id="pNote"></div></div><button class="btn" onclick="addProduction()">Simpan Hasil Produksi</button></div><div class="card"><h2>Rekap Produksi</h2><table><thead><tr><th>Tanggal</th><th>Produk</th><th class="num">Good</th><th class="num">Reject</th><th>Catatan</th></tr></thead><tbody>${db.productions.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${x.productName}</td><td class="num">${fmt(x.qty)}</td><td class="num">${fmt(x.reject)}</td><td>${x.note||'-'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Belum ada produksi</td></tr>'}</tbody></table></div>`}
window.addProduction=()=>{let p=db.products.find(x=>x.id===$('#pProduct').value),q=Number($('#pQty').value),r=Number($('#pReject').value||0);if(!p||q<=0)return alert('Qty produksi harus lebih dari 0.');db.fgStock[p.id]=(Number(db.fgStock[p.id])||0)+q;db.productions.push({id:uid('P'),date:$('#pDate').value,productId:p.id,productName:p.name,qty:q,reject:r,note:$('#pNote').value});save()}
function renderStock(){let rowsRM=db.materials.map(x=>`<tr><td>${x.id}</td><td>${x.name}</td><td>${x.unit}</td><td class="num">${fmt(x.stock)}</td><td class="num">${money(x.avgCost)}</td><td>${x.stock<=x.minStock?'<span class="badge bad">KRITIS</span>':'<span class="badge ok">OK</span>'}</td></tr>`).join(''),rowsPK=db.packaging.map(x=>`<tr><td>${x.id}</td><td>${x.name}</td><td>${x.type}</td><td>${x.unit}</td><td class="num">${fmt(x.stock)}</td><td>${x.stock<=x.minStock?'<span class="badge bad">KRITIS</span>':'<span class="badge ok">OK</span>'}</td></tr>`).join(''),rowsFG=db.products.map(x=>`<tr><td>${x.id}</td><td>${x.name}</td><td class="num">${fmt(db.fgStock[x.id]||0)}</td><td>${(db.fgStock[x.id]||0)<=x.minStock?'<span class="badge bad">LOW</span>':'<span class="badge ok">OK</span>'}</td></tr>`).join('');$('#stock').innerHTML=`<div class="card"><h2>Stok Raw Material</h2><table><tr><th>Kode</th><th>Item</th><th>Sat</th><th class="num">Stok</th><th class="num">Avg Cost</th><th>Status</th></tr>${rowsRM}</table></div><div class="card"><h2>Stok Packaging</h2><table><tr><th>Kode</th><th>Item</th><th>Jenis</th><th>Sat</th><th class="num">Stok</th><th>Status</th></tr>${rowsPK}</table></div><div class="card"><h2>Stok Finish Good</h2><table><tr><th>Kode</th><th>Produk</th><th class="num">Stok</th><th>Status</th></tr>${rowsFG}</table></div>`}
function renderReports(){let done=db.orders.filter(o=>o.status==='SELESAI'),reg=done.filter(o=>o.type==='REGULER'),res=done.filter(o=>o.type==='RESELLER'),sum=a=>a.reduce((s,o)=>s+orderTotals(o).subtotal,0),prof=a=>a.reduce((s,o)=>s+orderTotals(o).profit,0);$('#reports').innerHTML=`<div class="card no-print"><h2>Filter Laporan</h2><div class="row3"><div><label>Dari</label><input id="rFrom" type="date"></div><div><label>Sampai</label><input id="rTo" type="date"></div><div><label>Jenis Order</label><select id="rType"><option value="ALL">SEMUA</option><option>REGULER</option><option>RESELLER</option></select></div></div><div class="actions"><button class="btn" onclick="applyReport()">Tampilkan</button><button class="btn secondary" onclick="window.print()">Print Laporan</button></div></div><div id="reportBody">${reportHtml(done)}</div>`}
function reportHtml(arr){let omzet=arr.reduce((s,o)=>s+orderTotals(o).subtotal,0),hpp=arr.reduce((s,o)=>s+orderTotals(o).hpp,0),profit=omzet-hpp;return`<div class="grid3"><div class="kpi"><b>${money(omzet)}</b><span>Penjualan</span></div><div class="kpi"><b>${money(hpp)}</b><span>HPP</span></div><div class="kpi"><b>${money(profit)}</b><span>Profit Kotor</span></div></div><div class="card"><h2>Laporan Penjualan & Profit</h2><table><thead><tr><th>Tanggal</th><th>No Order</th><th>Pelanggan</th><th>Jenis</th><th class="num">Penjualan</th><th class="num">HPP</th><th class="num">Profit</th></tr></thead><tbody>${arr.map(o=>{let t=orderTotals(o);return`<tr><td>${o.date}</td><td>${o.no}</td><td>${o.customer}</td><td>${o.type}</td><td class="num">${money(t.subtotal)}</td><td class="num">${money(t.hpp)}</td><td class="num">${money(t.profit)}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Belum ada penjualan selesai</td></tr>'}</tbody></table></div>`}
window.applyReport=()=>{let f=$('#rFrom').value,t=$('#rTo').value,ty=$('#rType').value,a=db.orders.filter(o=>o.status==='SELESAI'&&(!f||o.date>=f)&&(!t||o.date<=t)&&(ty==='ALL'||o.type===ty));$('#reportBody').innerHTML=reportHtml(a)}
function renderSettings(){$('#settings').innerHTML=`<div class="card"><h2>Master Produk FG</h2><div class="row3 no-print"><input id="mProdName" placeholder="Nama produk"><input id="mProdReg" type="number" placeholder="Harga reguler"><input id="mProdRes" type="number" placeholder="Harga reseller"><input id="mProdHpp" type="number" placeholder="HPP/pcs"><input id="mProdMin" type="number" placeholder="Stok minimum"><button class="btn" onclick="addMasterProduct()">Tambah Produk</button></div><table><tr><th>Produk</th><th class="num">Reguler</th><th class="num">Reseller</th><th class="num">HPP</th></tr>${db.products.map(x=>`<tr><td>${x.id} - ${x.name}</td><td class="num">${money(x.priceRegular)}</td><td class="num">${money(x.priceReseller)}</td><td class="num">${money(x.hpp)}</td></tr>`).join('')}</table></div>
<div class="card"><h2>Master Raw Material</h2><div class="row3 no-print"><input id="mRMName" placeholder="Nama raw material"><input id="mRMUnit" placeholder="Satuan"><input id="mRMMin" type="number" placeholder="Stok minimum"><button class="btn" onclick="addMasterRM()">Tambah RM</button></div><table>${db.materials.map(x=>`<tr><td>${x.id}</td><td>${x.name}</td><td>${x.unit}</td><td class="num">Min ${fmt(x.minStock)}</td></tr>`).join('')}</table></div>
<div class="card"><h2>Master Packaging</h2><div class="row3 no-print"><input id="mPKName" placeholder="Nama packaging"><select id="mPKType"><option>INNER</option><option>OUTER</option></select><input id="mPKUnit" placeholder="Satuan"><input id="mPKMin" type="number" placeholder="Stok minimum"><button class="btn" onclick="addMasterPK()">Tambah Packaging</button></div><table>${db.packaging.map(x=>`<tr><td>${x.id}</td><td>${x.name}</td><td>${x.type}</td><td>${x.unit}</td><td class="num">Min ${fmt(x.minStock)}</td></tr>`).join('')}</table></div>
<div class="card no-print"><h2>Backup Data</h2><p class="small">Simpan backup secara berkala. Data utama tersimpan lokal di perangkat.</p><div class="actions"><button class="btn secondary" onclick="backupData()">Download Backup JSON</button><label class="btn secondary" style="text-align:center">Restore Backup<input id="restoreFile" type="file" accept="application/json" style="display:none" onchange="restoreData(event)"></label><button class="btn danger" onclick="resetData()">Reset Semua Data</button></div></div>`}
window.addMasterProduct=()=>{let name=$('#mProdName').value.trim();if(!name)return;let id='FG'+String(db.products.length+1).padStart(3,'0');db.products.push({id,name,unit:'pcs',priceRegular:Number($('#mProdReg').value),priceReseller:Number($('#mProdRes').value),hpp:Number($('#mProdHpp').value),minStock:Number($('#mProdMin').value)});db.fgStock[id]=0;save()}
window.addMasterRM=()=>{let name=$('#mRMName').value.trim();if(!name)return;db.materials.push({id:'RM'+String(db.materials.length+1).padStart(3,'0'),name,unit:$('#mRMUnit').value||'pcs',stock:0,avgCost:0,minStock:Number($('#mRMMin').value)});save()}
window.addMasterPK=()=>{let name=$('#mPKName').value.trim();if(!name)return;db.packaging.push({id:'PK'+String(db.packaging.length+1).padStart(3,'0'),name,type:$('#mPKType').value,unit:$('#mPKUnit').value||'pcs',stock:0,avgCost:0,minStock:Number($('#mPKMin').value)});save()}
window.backupData=()=>{let b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='mini-erp-backup-'+today()+'.json';a.click();URL.revokeObjectURL(a.href)}
window.restoreData=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();alert('Backup berhasil direstore.')}catch(err){alert('File backup tidak valid.')}};r.readAsText(f)}
window.resetData=()=>{if(confirm('Hapus semua data aplikasi?')){db=structuredClone(seed);save()}}
buildNav();render('dashboard');setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),1000);
