window.addEventListener('error',function(e){try{const d=document.querySelector('#dashboard');if(d&&!d.innerHTML.trim()){d.innerHTML='<div class="card"><h2>Aplikasi sedang memuat ulang</h2><p class="small">Versi cache lama terdeteksi. Refresh halaman sekali lagi.</p></div>';}}catch(_){}});
const $=s=>document.querySelector(s);
const fmt=n=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(Number(n)||0);
const money=n=>'Rp '+new Intl.NumberFormat('id-ID').format(Math.round(Number(n)||0));
const today=()=>{const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const uid=p=>p+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const DBKEY='miniERPProduksi_v1';
const PRINTKEY='cemilanMomcip_printWidth';
const getPrintWidth=()=>localStorage.getItem(PRINTKEY)||'80';
const seed={
  products:[
    {id:'FG001',name:'Samosa Ayam',unit:'pcs',packSize:10,priceRegular:3500,priceRegularPack:35000,priceReseller:2800,priceResellerPack:28000,hpp:1850,minStock:20},
    {id:'FG002',name:'Samosa Keju',unit:'pcs',packSize:10,priceRegular:4000,priceRegularPack:40000,priceReseller:3200,priceResellerPack:32000,hpp:2100,minStock:20}
  ],
  materials:[
    {id:'RM001',name:'Daging Ayam',unit:'gram',stock:0,avgCost:0,minStock:2000},
    {id:'RM002',name:'Kulit Samosa',unit:'pcs',stock:0,avgCost:0,minStock:100}
  ],
  packaging:[
    {id:'PK001',name:'Plastik Inner',type:'INNER',unit:'pcs',stock:0,avgCost:0,minStock:100},
    {id:'PK002',name:'Master Carton',type:'OUTER',unit:'pcs',stock:0,avgCost:0,minStock:10}
  ],
  fgStock:{FG001:0,FG002:0},orders:[],materialTx:[],packagingTx:[],productions:[]
};
let db=load();
let active='dashboard';
let currentReport=[];
let orderDraftItems=[];
const orderTypeLabel=v=>String(v||'').toUpperCase()==='RESELLER'?'Reseller':'Reguler';
const unitLabel=v=>String(v||'').toUpperCase()==='PACK'?'Pack':'Pcs';
const packTypeLabel=v=>String(v||'').toUpperCase()==='OUTER'?'Outer':'Inner';
const txModeLabel=v=>String(v||'').toUpperCase()==='IN'?'Pembelian / Masuk':'Pemakaian / Keluar';
function cloneSeed(){return JSON.parse(JSON.stringify(seed))}
function load(){
 try{
  const base=cloneSeed();
  const raw=JSON.parse(localStorage.getItem(DBKEY)||'{}')||{};
  const out=Object.assign(base,raw);
  out.products=Array.isArray(raw.products)?raw.products:base.products;
  out.materials=Array.isArray(raw.materials)?raw.materials:base.materials;
  out.packaging=Array.isArray(raw.packaging)?raw.packaging:base.packaging;
  out.orders=Array.isArray(raw.orders)?raw.orders:[];
  out.materialTx=Array.isArray(raw.materialTx)?raw.materialTx:[];
  out.packagingTx=Array.isArray(raw.packagingTx)?raw.packagingTx:[];
  out.productions=Array.isArray(raw.productions)?raw.productions:[];
  out.fgStock=Object.assign({},base.fgStock,(raw.fgStock&&typeof raw.fgStock==='object')?raw.fgStock:{});
  out.products=out.products.map(p=>{
   const packSize=Math.max(1,Number(p?.packSize)||1);
   const reg=Number(p?.priceRegular)||0, res=Number(p?.priceReseller)||0;
   return Object.assign({unit:'pcs',hpp:0,minStock:0},p||{}, {
    packSize,
    priceRegular:reg,
    priceReseller:res,
    priceRegularPack:Number(p?.priceRegularPack)||reg*packSize,
    priceResellerPack:Number(p?.priceResellerPack)||res*packSize
   });
  });
  out.materials=out.materials.map(x=>Object.assign({unit:'pcs',stock:0,avgCost:0,minStock:0},x||{}));
  out.packaging=out.packaging.map(x=>Object.assign({type:'INNER',unit:'pcs',stock:0,avgCost:0,minStock:0},x||{}));
  out.orders=out.orders.map(o=>Object.assign({status:'BARU',items:[]},o||{}, {items:Array.isArray(o?.items)?o.items:[]}));
  return out;
 }catch(e){console.error('Load DB gagal, memakai seed.',e);return cloneSeed()}
}
function save(){localStorage.setItem(DBKEY,JSON.stringify(db));render(active)}
const pages=[
 ['dashboard','⌂','Home'],['order','🧾','Order'],['material','🥩','Raw Material'],['packaging','📦','Packaging'],
 ['production','🍳','Produksi'],['stock','🗃️','Stok'],['reports','📊','Laporan'],['settings','⚙️','Master']
];
function buildNav(){
 $('#bottomnav').innerHTML=pages.map(([id,ico,n])=>`<button data-nav="${id}" onclick="nav('${id}')"><span class="ico">${ico}</span>${n}</button>`).join('');
}
function nav(id){active=id;document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));render(id);scrollTo(0,0)}
function render(id){document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));({dashboard:renderDashboard,order:renderOrder,material:renderMaterial,packaging:renderPackaging,production:renderProduction,stock:renderStock,reports:renderReports,settings:renderSettings}[id]||(()=>{}))()}
function orderTotals(o){const subtotal=(o.items||[]).reduce((s,i)=>s+(Number.isFinite(Number(i.lineTotal))?Number(i.lineTotal):Number(i.qty)*Number(i.price)),0);const hpp=(o.items||[]).reduce((s,i)=>s+Number(i.qty)*Number(i.hpp),0);return{subtotal,hpp,profit:subtotal-hpp}}
function itemOrderLabel(i){let u=(i.orderUnit||'PCS').toUpperCase(),q=Number(i.orderQty??i.qty)||0;return `${fmt(q)} ${unitLabel(u)}${u==='PACK'&&Number(i.packSize)>0?` (${fmt(i.qty)} Pcs)`:''}`}
function itemUnitPrice(i){return Number(i.unitPrice??i.price)||0}
function openOrders(){return db.orders.filter(o=>o.status!=='SELESAI'&&o.status!=='BATAL')}
function outstandingByProduct(){const r={};db.products.forEach(p=>r[p.id]={product:p,orderQty:0,stock:Number(db.fgStock[p.id]||0),need:0});openOrders().forEach(o=>(o.items||[]).forEach(i=>{if(r[i.productId])r[i.productId].orderQty+=Number(i.qty)||0}));Object.values(r).forEach(x=>x.need=Math.max(0,x.orderQty-x.stock));return Object.values(r)}
function dateID(s){if(!s)return'-';let [y,m,d]=s.split('-');return `${d}/${m}/${y}`}
function printWindow(title,body,mode='report'){
 const w=window.open('','_blank');if(!w)return alert('Popup diblokir browser. Izinkan popup untuk mencetak.');
 const thermal=mode==='thermal', width=getPrintWidth();
 const pageCss=thermal?`@page{size:${width}mm auto;margin:2mm}body{width:${width-4}mm;margin:0 auto;font-size:${width==='57'?'9px':'10px'}}`:'@page{size:A4 landscape;margin:8mm}body{margin:0;font-size:11px}';
 w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>${pageCss}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#222}.head{display:flex;align-items:center;gap:10px;border-bottom:1px solid #444;padding-bottom:7px;margin-bottom:9px}.head img{width:${thermal?'44':'64'}px;height:${thermal?'44':'64'}px;border-radius:50%;object-fit:cover}.head h1{margin:0;font-size:${thermal?'16':'22'}px;color:#60301f}.tagline{font-size:${thermal?'8':'11'}px}.muted{color:#666}.summary{display:grid;grid-template-columns:repeat(${thermal?'2':'3'},1fr);gap:6px;margin:10px 0}.box{border:1px solid #bbb;padding:7px;border-radius:6px}.box b{font-size:${thermal?'12':'15'}px;display:block}table{width:100%;border-collapse:collapse;margin-top:8px;table-layout:auto}.report table{width:auto;max-width:100%;margin-left:0;margin-right:auto}.report th,.report td{width:auto}.report .num{white-space:nowrap}.thermal table{width:100%}th,td{border:1px solid #bbb;padding:${thermal?'3px 2px':'5px 4px'};vertical-align:top}th{background:#fff0ee;text-align:left;font-size:${thermal?'7':'9'}px}.num{text-align:right;white-space:nowrap}.center{text-align:center}h2{font-size:${thermal?'12':'15'}px;margin:12px 0 6px}.receipt-table td,.receipt-table th{border-left:0;border-right:0}.receipt-items{margin-top:8px}.receipt-item{padding:6px 0;border-bottom:1px dashed #aaa}.receipt-line{display:flex;justify-content:space-between;gap:6px;margin-top:3px;font-size:${thermal?'9':'11'}px}.receipt-grand{display:flex;justify-content:space-between;border-top:1px solid #555;border-bottom:1px solid #aaa;padding:7px 2px;margin-top:4px;font-size:${thermal?'13':'16'}px}.need-head{white-space:normal;min-width:${thermal?'48px':'70px'};line-height:1.1}.receipt-total{font-size:${thermal?'13':'16'}px;font-weight:800}.chartbox{border:1px solid #bbb;padding:8px;border-radius:8px;margin:10px 0}.chartbox svg{width:100%;height:auto;display:block}.twocharts{display:grid;grid-template-columns:1fr 1fr;gap:10px}.chart-full{break-inside:avoid;page-break-inside:avoid}.compact{font-size:9px}.compact th,.compact td{padding:3px}.pagebreak{break-before:page;page-break-before:always}@media print{.no-print{display:none}.twocharts{grid-template-columns:1fr 1fr}h2{break-after:avoid;page-break-after:avoid}table,.summary,.chartbox{break-inside:avoid;page-break-inside:avoid}.chartbox{margin:6px 0;padding:5px}.head{margin-bottom:6px}.summary{margin:6px 0;gap:4px}.box{padding:5px}.compact{font-size:8px}.compact th,.compact td{padding:2px 3px}}</style></head><body class="${mode}"><div class="head"><img src="logo.jpg"><div><h1>CEMILAN MOMCIP</h1><div class="tagline">Homemade Snack &amp; Drink With Love</div><div class="muted">0821-1290-2549</div></div></div>${body}<script>window.onload=()=>setTimeout(()=>window.print(),350)<\/script></body></html>`);w.document.close()
}
window.printOutstanding=()=>{
 const rows=outstandingByProduct();
 const totalNeed=rows.reduce((s,x)=>s+x.need,0);
 printWindow('Outstanding Produksi',`<h2>OUTSTANDING PRODUKSI</h2><div class="muted">Tanggal cetak: ${new Date().toLocaleString('id-ID')}</div><div class="summary"><div class="box"><b>${openOrders().length}</b>Order aktif</div><div class="box"><b>${rows.filter(x=>x.need>0).length}</b>Produk perlu produksi</div><div class="box"><b>${fmt(totalNeed)}</b>Total qty perlu produksi</div></div><table><thead><tr><th>Produk</th><th class="num">Order</th><th class="num">Stok FG</th><th class="num need-head">Perlu Produksi</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.product.name)}</td><td class="num">${fmt(x.orderQty)}</td><td class="num">${fmt(x.stock)}</td><td class="num"><b>${fmt(x.need)}</b></td></tr>`).join('')}</tbody></table>`, 'thermal')
}


function renderDashboard(){
 const out=outstandingByProduct();
 const activeOrders=openOrders();
 const needCount=out.filter(x=>x.need>0).length;
 const criticalRM=db.materials.filter(x=>Number(x.stock||0)<=Number(x.minStock||0)).length;
 const criticalPK=db.packaging.filter(x=>Number(x.stock||0)<=Number(x.minStock||0)).length;
 const criticalFG=db.products.filter(p=>Number(db.fgStock[p.id]||0)<=Number(p.minStock||0)).length;
 const completed=db.orders.filter(o=>o.status==='SELESAI');
 const sales=completed.reduce((s,o)=>s+orderTotals(o).subtotal,0);
 const profit=completed.reduce((s,o)=>s+orderTotals(o).profit,0);
 const prodQty=db.productions.reduce((s,p)=>s+Number(p.qty||0),0);
 const rows=out.map(x=>`<tr><td>${esc(x.product.name)}</td><td class="num">${fmt(x.orderQty)}</td><td class="num">${fmt(x.stock)}</td><td class="num"><b>${fmt(x.need)}</b></td></tr>`).join('');
 $('#dashboard').innerHTML=`
  <div class="grid3">
   <div class="kpi"><b>${activeOrders.length}</b><span>Order aktif</span></div>
   <div class="kpi"><b>${needCount}</b><span>Produk perlu produksi</span></div>
   <div class="kpi"><b>${criticalRM+criticalPK+criticalFG}</b><span>Item stok kritis</span></div>
   <div class="kpi"><b>${money(sales)}</b><span>Total penjualan selesai</span></div>
   <div class="kpi"><b>${money(profit)}</b><span>Total profit kotor</span></div>
   <div class="kpi"><b>${fmt(prodQty)}</b><span>Total hasil produksi</span></div>
  </div>
  <div class="card" style="margin-top:12px">
   <div class="cardhead"><h2>Outstanding Produksi</h2><button class="btn secondary smallbtn no-print" onclick="printOutstanding()">🖨 Print</button></div>
   <div class="tablewrap autofit compact"><table><thead><tr><th>Produk</th><th class="num">Order Aktif</th><th class="num">Stok FG</th><th class="num">Perlu Produksi</th></tr></thead><tbody>${rows||'<tr><td colspan="4" class="empty">Belum ada master produk</td></tr>'}</tbody></table></div>
  </div>`;
}

function nextOrderNo(dateStr){
 const compact=(dateStr||today()).replace(/-/g,'').slice(2);
 const prefix=`CM-${compact}-`;
 let max=0;
 db.orders.forEach(o=>{if(String(o.no||'').startsWith(prefix)){const n=Number(String(o.no).slice(prefix.length));if(Number.isFinite(n))max=Math.max(max,n)}});
 return prefix+String(max+1).padStart(3,'0')
}
function renderDraftItems(){
 const box=$('#orderDraftList');if(!box)return;
 if(!orderDraftItems.length){box.innerHTML='<div class="empty">Belum ada item. Tambahkan minimal 1 item.</div>';return}
 let total=orderDraftItems.reduce((s,i)=>s+Number(i.lineTotal||0),0);
 box.innerHTML=`<div class="tablewrap fit"><table><thead><tr><th>Produk</th><th>Qty</th><th class="num">Harga</th><th class="num">Jumlah</th><th>Aksi</th></tr></thead><tbody>${orderDraftItems.map((i,idx)=>`<tr><td>${esc(i.name)}</td><td>${itemOrderLabel(i)}</td><td class="num">${money(itemUnitPrice(i))}</td><td class="num">${money(i.lineTotal)}</td><td><button class="btn danger smallbtn" onclick="removeOrderItem(${idx})">Hapus</button></td></tr>`).join('')}<tr><td colspan="3"><b>Total</b></td><td class="num"><b>${money(total)}</b></td><td></td></tr></tbody></table></div>`
}
function renderOrder(){
 const prodOpts=db.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');
 const rows=db.orders.slice().reverse();
 const desktop=rows.map(o=>{let t=orderTotals(o);return`<tr><td>${esc(o.no)}<div class="small">${dateID(o.date)}</div></td><td>${esc(o.customer)}</td><td><span class="badge ${String(o.type).toUpperCase()==='RESELLER'?'res':'reg'}">${orderTypeLabel(o.type)}</span></td><td>${(o.items||[]).map(i=>`${esc(i.name)} × ${itemOrderLabel(i)}`).join('<br>')}</td><td class="num">${money(t.subtotal)}</td><td><span class="badge ${o.status==='SELESAI'?'ok':''}">${esc(o.status)}</span></td><td class="no-print"><div class="actions" style="margin:0"><button class="btn secondary smallbtn" onclick="printReceipt('${o.id}')">Struk</button>${o.status!=='SELESAI'?`<button class="btn ok smallbtn" onclick="finishOrder('${o.id}')">Selesai</button>`:''}</div></td></tr>`}).join('');
 const mobile=rows.map(o=>{let t=orderTotals(o);return`<div class="ordercard"><div class="top"><b>${esc(o.customer)}</b><span class="badge ${String(o.type).toUpperCase()==='RESELLER'?'res':'reg'}">${orderTypeLabel(o.type)}</span></div><div class="small">${esc(o.no)} • ${dateID(o.date)}</div><div class="kv"><span>Item</span><b>${(o.items||[]).map(i=>`${esc(i.name)} × ${itemOrderLabel(i)}`).join(', ')}</b><span>Total</span><b>${money(t.subtotal)}</b><span>Status</span><b>${esc(o.status)}</b></div><div class="actions no-print"><button class="btn secondary smallbtn" onclick="printReceipt('${o.id}')">🖨 Struk</button>${o.status!=='SELESAI'?`<button class="btn ok smallbtn" onclick="finishOrder('${o.id}')">✓ Selesai</button>`:''}</div></div>`}).join('');
 $('#order').innerHTML=`<div class="card no-print"><h2>Input Order</h2><div class="row"><div><label>Tanggal</label><input id="oDate" type="date" value="${today()}"></div><div><label>Jenis Order</label><select id="oType" onchange="syncOrderPrice()"><option value="REGULER">Reguler</option><option value="RESELLER">Reseller</option></select></div><div class="full"><label>Nama Pelanggan</label><input id="oCustomer" placeholder="Nama pelanggan"></div></div><h3>Tambah Item</h3><div class="row"><div><label>Produk</label><select id="oProduct" onchange="syncOrderPrice()">${prodOpts}</select></div><div><label>Qty</label><input id="oQty" type="number" min="1" value="1"></div><div><label>Unit</label><select id="oUnit" onchange="syncOrderPrice()"><option value="PCS">Pcs</option><option value="PACK">Pack</option></select></div><div><label>Harga / Unit</label><input id="oPrice" type="number"></div><div class="full"><label>Konversi</label><input id="oConvert" readonly></div></div><button class="btn secondary" style="width:100%" onclick="addOrderItem()">+ Tambah Item</button><div id="orderDraftList" style="margin-top:10px"></div><button class="btn" style="width:100%;margin-top:10px" onclick="saveOrder()">Simpan Order</button></div>
 <div class="card"><h2>Rekap Order</h2><div class="desktop-table tablewrap"><table><thead><tr><th>No Order</th><th>Pelanggan</th><th>Jenis</th><th>Item</th><th class="num">Total</th><th>Status</th><th class="no-print">Aksi</th></tr></thead><tbody>${desktop||'<tr><td colspan="7" class="empty">Belum ada order</td></tr>'}</tbody></table></div><div class="mobilelist">${mobile||'<div class="empty">Belum ada order</div>'}</div></div>`;
 setTimeout(()=>{syncOrderPrice();renderDraftItems()},0)
}
window.syncOrderPrice=()=>{let p=db.products.find(x=>x.id===$('#oProduct')?.value),unit=$('#oUnit')?.value||'PCS',type=$('#oType')?.value||'REGULER';if(!p)return;let price=unit==='PACK'?(type==='RESELLER'?p.priceResellerPack:p.priceRegularPack):(type==='RESELLER'?p.priceReseller:p.priceRegular);if($('#oPrice'))$('#oPrice').value=Number(price)||0;if($('#oConvert'))$('#oConvert').value=unit==='PACK'?`1 Pack = ${fmt(p.packSize||1)} Pcs`:'1 Pcs = 1 Pcs'}
window.addOrderItem=()=>{let p=db.products.find(x=>x.id===$('#oProduct')?.value),orderQty=Number($('#oQty')?.value),unit=$('#oUnit')?.value||'PCS',unitPrice=Number($('#oPrice')?.value);if(!p||orderQty<=0||unitPrice<0)return alert('Pilih produk dan isi qty/harga dengan benar.');let packSize=Number(p.packSize)||1,qty=unit==='PACK'?orderQty*packSize:orderQty,lineTotal=orderQty*unitPrice,pricePerPcs=qty?lineTotal/qty:0;orderDraftItems.push({productId:p.id,name:p.name,qty,orderQty,orderUnit:unit,packSize,unitPrice,lineTotal,price:pricePerPcs,hpp:p.hpp});renderDraftItems();$('#oQty').value=1}
window.removeOrderItem=idx=>{orderDraftItems.splice(idx,1);renderDraftItems()}
window.saveOrder=()=>{let customer=$('#oCustomer')?.value.trim(),date=$('#oDate')?.value||today(),type=$('#oType')?.value||'REGULER';if(!customer)return alert('Nama pelanggan wajib diisi.');if(!orderDraftItems.length)return alert('Tambahkan minimal 1 item order.');let no=nextOrderNo(date);db.orders.push({id:uid('O'),no,date,type,customer,status:'BARU',items:orderDraftItems.map(i=>({...i}))});orderDraftItems=[];save()}
window.addOrder=window.saveOrder
window.finishOrder=id=>{let o=db.orders.find(x=>x.id===id);if(!o)return;for(const i of o.items){let st=Number(db.fgStock[i.productId]||0);if(st<i.qty)return alert(`Stok ${i.name} tidak cukup. Stok ${fmt(st)} Pcs, kebutuhan ${fmt(i.qty)} Pcs.`)}if(!confirm('Tandai order selesai dan kurangi stok FG?'))return;o.items.forEach(i=>db.fgStock[i.productId]-=Number(i.qty));o.status='SELESAI';o.completedAt=new Date().toISOString();save()}
window.printReceipt=id=>{let o=db.orders.find(x=>x.id===id);if(!o)return;let t=orderTotals(o);printWindow('Struk '+o.no,`<div class="center"><h2>STRUK ORDER</h2></div><table class="receipt-table"><tr><td>No Order</td><td>${esc(o.no)}</td></tr><tr><td>Tanggal</td><td>${dateID(o.date)}</td></tr><tr><td>Pelanggan</td><td>${esc(o.customer)}</td></tr><tr><td>Jenis</td><td>${orderTypeLabel(o.type)}</td></tr></table><div class="receipt-items">${o.items.map(i=>`<div class="receipt-item"><b>${esc(i.name)}</b><div class="receipt-line"><span>${itemOrderLabel(i)} × ${money(itemUnitPrice(i))}</span><b>${money(Number.isFinite(Number(i.lineTotal))?Number(i.lineTotal):Number(i.qty)*Number(i.price))}</b></div></div>`).join('')}</div><div class="receipt-grand"><b>TOTAL</b><b>${money(t.subtotal)}</b></div><p class="center">Terima kasih atas pesanan Anda.<br>Semoga suka dengan produknya! ♥</p>`,'thermal')}

function txForm(kind){let isRM=kind==='material',arr=isRM?db.materials:db.packaging,opts=arr.map(x=>`<option value="${x.id}">${esc(x.name)}${isRM?'':' - '+packTypeLabel(x.type)}</option>`).join('');return`<div class="card no-print"><h2>${isRM?'Transaksi Raw Material':'Transaksi Packaging'}</h2><div class="row3"><div><label>Tanggal</label><input id="${kind}Date" type="date" value="${today()}"></div><div><label>Jenis Transaksi</label><select id="${kind}Mode"><option value="IN">Pembelian / Masuk</option><option value="OUT">Pemakaian / Keluar</option></select></div><div><label>Item</label><select id="${kind}Item">${opts}</select></div><div><label>Qty</label><input id="${kind}Qty" type="number" min="0" step="0.01"></div><div><label>Harga/unit (pembelian)</label><input id="${kind}Cost" type="number" min="0" step="0.01" value="0"></div><div><label>Keterangan</label><input id="${kind}Note" placeholder="Supplier / produksi / catatan"></div></div><button class="btn" onclick="addTx('${kind}')">Simpan Transaksi</button></div>`}
window.addTx=kind=>{let isRM=kind==='material',arr=isRM?db.materials:db.packaging,txs=isRM?db.materialTx:db.packagingTx,item=arr.find(x=>x.id===$(`#${kind}Item`).value),mode=$(`#${kind}Mode`).value,qty=Number($(`#${kind}Qty`).value),cost=Number($(`#${kind}Cost`).value||0);if(!item||qty<=0)return alert('Pilih item dan isi qty.');if(mode==='OUT'&&item.stock<qty)return alert('Stok tidak cukup.');if(mode==='IN'){let oldVal=item.stock*item.avgCost,newVal=qty*cost;item.stock+=qty;item.avgCost=item.stock?((oldVal+newVal)/item.stock):0}else item.stock-=qty;txs.push({id:uid('T'),date:$(`#${kind}Date`).value,itemId:item.id,itemName:item.name,mode,qty,cost,note:$(`#${kind}Note`).value});save()}
function txTable(txs,title){return`<div class="card"><h2>Rekap ${title}</h2><div class="tablewrap fit"><table><thead><tr><th>Tanggal</th><th>Item</th><th>Transaksi</th><th class="num">Qty</th><th class="num">Harga</th><th>Catatan</th></tr></thead><tbody>${txs.slice().reverse().map(x=>`<tr><td>${dateID(x.date)}</td><td>${esc(x.itemName)}</td><td>${x.mode==='IN'?'Pembelian / Masuk':'Pemakaian / Keluar'}</td><td class="num">${fmt(x.qty)}</td><td class="num">${x.mode==='IN'?money(x.cost):'-'}</td><td>${esc(x.note||'-')}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Belum ada transaksi</td></tr>'}</tbody></table></div></div>`}
function renderMaterial(){$('#material').innerHTML=txForm('material')+txTable(db.materialTx,'Raw Material')}
function renderPackaging(){$('#packaging').innerHTML=txForm('packaging')+txTable(db.packagingTx,'Packaging')}

function renderProduction(){let opts=db.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('#production').innerHTML=`<div class="card no-print"><h2>Input Hasil Produksi</h2><div class="row"><div><label>Tanggal</label><input id="pDate" type="date" value="${today()}"></div><div><label>Produk</label><select id="pProduct">${opts}</select></div><div><label>Qty Good</label><input id="pQty" type="number" min="1"></div><div><label>Reject</label><input id="pReject" type="number" min="0" value="0"></div><div class="full"><label>Catatan / Batch</label><input id="pNote"></div></div><button class="btn" onclick="addProduction()">Simpan Hasil Produksi</button></div><div class="card"><h2>Rekap Produksi</h2><div class="tablewrap fit"><table><thead><tr><th>Tanggal</th><th>Produk</th><th class="num">Good</th><th class="num">Reject</th><th>Catatan</th></tr></thead><tbody>${db.productions.slice().reverse().map(x=>`<tr><td>${dateID(x.date)}</td><td>${esc(x.productName)}</td><td class="num">${fmt(x.qty)}</td><td class="num">${fmt(x.reject)}</td><td>${esc(x.note||'-')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Belum ada produksi</td></tr>'}</tbody></table></div></div>`}
window.addProduction=()=>{let p=db.products.find(x=>x.id===$('#pProduct').value),q=Number($('#pQty').value),r=Number($('#pReject').value||0);if(!p||q<=0)return alert('Qty produksi harus lebih dari 0.');db.fgStock[p.id]=(Number(db.fgStock[p.id])||0)+q;db.productions.push({id:uid('P'),date:$('#pDate').value,productId:p.id,productName:p.name,qty:q,reject:r,note:$('#pNote').value});save()}

function renderStock(){let rowsRM=db.materials.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.name)}</td><td>${esc(x.unit)}</td><td class="num">${fmt(x.stock)}</td><td class="num">${money(x.avgCost)}</td><td>${x.stock<=x.minStock?'<span class="badge bad">KRITIS</span>':'<span class="badge ok">OK</span>'}</td></tr>`).join(''),rowsPK=db.packaging.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.name)}</td><td>${packTypeLabel(x.type)}</td><td>${esc(x.unit)}</td><td class="num">${fmt(x.stock)}</td><td>${x.stock<=x.minStock?'<span class="badge bad">KRITIS</span>':'<span class="badge ok">OK</span>'}</td></tr>`).join(''),rowsFG=db.products.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.name)}</td><td class="num">${fmt(db.fgStock[x.id]||0)}</td><td>${(db.fgStock[x.id]||0)<=x.minStock?'<span class="badge bad">LOW</span>':'<span class="badge ok">OK</span>'}</td></tr>`).join('');$('#stock').innerHTML=`<div class="card"><h2>Stok Raw Material</h2><div class="tablewrap fit"><table><tr><th>Kode</th><th>Item</th><th>Sat</th><th class="num">Stok</th><th class="num">Avg Cost</th><th>Status</th></tr>${rowsRM}</table></div></div><div class="card"><h2>Stok Packaging</h2><div class="tablewrap fit"><table><tr><th>Kode</th><th>Item</th><th>Jenis</th><th>Sat</th><th class="num">Stok</th><th>Status</th></tr>${rowsPK}</table></div></div><div class="card"><h2>Stok Finish Good</h2><div class="tablewrap fit"><table><tr><th>Kode</th><th>Produk</th><th class="num">Stok</th><th>Status</th></tr>${rowsFG}</table></div></div>`}

function filteredOrders(){let f=$('#rFrom')?.value||'',t=$('#rTo')?.value||'',ty=$('#rType')?.value||'ALL';return db.orders.filter(o=>o.status==='SELESAI'&&(!f||o.date>=f)&&(!t||o.date<=t)&&(ty==='ALL'||o.type===ty))}
function itemMetrics(i){let pcs=Number(i.qtyPcs??i.qty??0),sales=Number.isFinite(Number(i.lineTotal))?Number(i.lineTotal):Number(i.qty||0)*Number(i.price||0),hpp=pcs*Number(i.hpp||0);return{qty:pcs,sales,hpp,profit:sales-hpp}}
function productSummary(arr){let m={};arr.forEach(o=>(o.items||[]).forEach(i=>{let k=i.productId||i.name;if(!m[k])m[k]={name:i.name,qty:0,sales:0,hpp:0,profit:0};let x=m[k],v=itemMetrics(i);x.qty+=v.qty;x.sales+=v.sales;x.hpp+=v.hpp;x.profit+=v.profit}));return Object.values(m).sort((a,b)=>b.sales-a.sales)}
function customerSummary(arr){let m={};arr.forEach(o=>{let k=(o.customer||'Tanpa Nama').trim()||'Tanpa Nama';if(!m[k])m[k]={name:k,qty:0,sales:0,hpp:0,profit:0};let x=m[k];(o.items||[]).forEach(i=>{let v=itemMetrics(i);x.qty+=v.qty;x.sales+=v.sales;x.hpp+=v.hpp;x.profit+=v.profit})});return Object.values(m).sort((a,b)=>b.sales-a.sales)}
function reportTotals(arr){let sales=0,hpp=0,qty=0;arr.forEach(o=>(o.items||[]).forEach(i=>{let v=itemMetrics(i);qty+=v.qty;sales+=v.sales;hpp+=v.hpp}));return{orders:arr.length,qty,sales,hpp,profit:sales-hpp,margin:sales?((sales-hpp)/sales*100):0}}
function dailySummary(arr){let m={};arr.forEach(o=>(o.items||[]).forEach(i=>{let customer=(o.customer||'Tanpa Nama').trim()||'Tanpa Nama',k=o.date+'|'+customer+'|'+(i.productId||i.name);if(!m[k])m[k]={date:o.date,customer,name:i.name,qty:0,sales:0,hpp:0,profit:0};let x=m[k],v=itemMetrics(i);x.qty+=v.qty;x.sales+=v.sales;x.hpp+=v.hpp;x.profit+=v.profit}));return Object.values(m).sort((a,b)=>a.date.localeCompare(b.date)||a.customer.localeCompare(b.customer)||a.name.localeCompare(b.name))}
function salesRange(start,end,type='ALL'){return db.orders.filter(o=>o.status==='SELESAI'&&o.date>=start&&o.date<=end&&(type==='ALL'||o.type===type))}
function periodBase(){let ref=$('#rTo')?.value||today(),d=new Date(ref+'T00:00:00'),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),last=new Date(y,d.getMonth()+1,0).getDate();return{ref,y,m,yStart:`${y}-01-01`,mStart:`${y}-${m}-01`,mEnd:`${y}-${m}-${String(last).padStart(2,'0')}`}}
function monthlySeries(arr,year){let out=Array.from({length:12},(_,i)=>({label:['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'][i],sales:0}));arr.forEach(o=>{let d=new Date(o.date+'T00:00:00');if(d.getFullYear()===year)out[d.getMonth()].sales+=reportTotals([o]).sales});return out}
function svgLineChart(data,title){let W=700,H=170,p=34,max=Math.max(1,...data.map(x=>x.sales)),pts=data.map((x,i)=>{let xx=p+i*((W-2*p)/Math.max(1,data.length-1)),yy=H-p-(x.sales/max)*(H-2*p);return[xx,yy]}),poly=pts.map(a=>a.join(',')).join(' '),labels=data.map((x,i)=>{let[xx,yy]=pts[i];return`<text x="${xx}" y="${H-10}" font-size="9" text-anchor="middle">${x.label}</text><circle cx="${xx}" cy="${yy}" r="3" fill="#e96c7c"/>`}).join('');return`<div class="chartbox"><b>${title}</b><svg viewBox="0 0 ${W} ${H}"><line x1="${p}" y1="${H-p}" x2="${W-p}" y2="${H-p}" stroke="#999"/><line x1="${p}" y1="${p}" x2="${p}" y2="${H-p}" stroke="#999"/><polyline points="${poly}" fill="none" stroke="#e96c7c" stroke-width="3"/>${labels}</svg></div>`}
function svgCustomerChart(arr,title){let data=customerSummary(arr).slice(0,7),W=700,H=180,p=38,max=Math.max(1,...data.map(x=>x.sales)),bw=(W-2*p)/Math.max(1,data.length),bars=data.map((x,i)=>{let h=(x.sales/max)*(H-2*p),xx=p+i*bw+bw*.15,yy=H-p-h,label=x.name.length>12?x.name.slice(0,11)+'…':x.name;return`<rect x="${xx}" y="${yy}" width="${bw*.7}" height="${h}" fill="#e96c7c"/><text x="${xx+bw*.35}" y="${H-10}" font-size="8" text-anchor="middle">${esc(label)}</text>`}).join('');return`<div class="chartbox"><b>${title}</b><svg viewBox="0 0 ${W} ${H}"><line x1="${p}" y1="${H-p}" x2="${W-p}" y2="${H-p}" stroke="#999"/>${bars}</svg></div>`}
function metricTable(title,rows,t){return`<h2>${title}</h2><table class="compact"><thead><tr><th>Nama</th><th class="num">Qty</th><th class="num">Penjualan</th><th class="num">HPP</th><th class="num">Profit</th><th class="num">Margin</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td class="num">${fmt(x.qty)}</td><td class="num">${money(x.sales)}</td><td class="num">${money(x.hpp)}</td><td class="num">${money(x.profit)}</td><td class="num">${x.sales?(x.profit/x.sales*100).toFixed(1):0}%</td></tr>`).join('')||'<tr><td colspan="6">Belum ada data</td></tr>'}<tr><td><b>TOTAL</b></td><td class="num"><b>${fmt(t.qty)}</b></td><td class="num"><b>${money(t.sales)}</b></td><td class="num"><b>${money(t.hpp)}</b></td><td class="num"><b>${money(t.profit)}</b></td><td class="num"><b>${t.margin.toFixed(1)}%</b></td></tr></tbody></table>`}
function summaryTable(title,arr){return metricTable(title,productSummary(arr),reportTotals(arr))}
function customerTable(title,arr){return metricTable(title,customerSummary(arr),reportTotals(arr))}
function reportHtml(arr){let t=reportTotals(arr),ds=dailySummary(arr);return`<div class="grid3"><div class="kpi"><b>${fmt(t.qty)}</b><span>Qty terjual (Pcs)</span></div><div class="kpi"><b>${money(t.sales)}</b><span>Penjualan</span></div><div class="kpi"><b>${money(t.hpp)}</b><span>HPP</span></div><div class="kpi"><b>${money(t.profit)}</b><span>Profit Kotor</span></div><div class="kpi"><b>${t.margin.toFixed(1)}%</b><span>Margin</span></div></div><div class="card"><h2>Detail Penjualan per Tanggal</h2><div class="tablewrap fit"><table><thead><tr><th>Tanggal</th><th>Pelanggan</th><th>Produk</th><th class="num">Qty Pcs</th><th class="num">Penjualan</th><th class="num">HPP</th><th class="num">Profit</th></tr></thead><tbody>${ds.map(x=>`<tr><td>${dateID(x.date)}</td><td>${esc(x.customer)}</td><td>${esc(x.name)}</td><td class="num">${fmt(x.qty)}</td><td class="num">${money(x.sales)}</td><td class="num">${money(x.hpp)}</td><td class="num">${money(x.profit)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Belum ada penjualan selesai</td></tr>'}</tbody></table></div></div>`}
function renderReports(){let now=new Date(),y=now.getFullYear(),m=String(now.getMonth()+1).padStart(2,'0'),last=String(new Date(y,now.getMonth()+1,0).getDate()).padStart(2,'0');currentReport=salesRange(`${y}-${m}-01`,`${y}-${m}-${last}`);$('#reports').innerHTML=`<div class="card no-print"><h2>Laporan</h2><div class="row3"><div><label>Dari</label><input id="rFrom" type="date" value="${y}-${m}-01"></div><div><label>Sampai</label><input id="rTo" type="date" value="${today()}"></div><div><label>Jenis Order</label><select id="rType"><option value="ALL">Semua</option><option value="REGULER">Reguler</option><option value="RESELLER">Reseller</option></select></div></div><h3>Penjualan</h3><div class="actions"><button class="btn" onclick="applyReport()">Tampilkan</button><button class="btn secondary" onclick="printSummaryReport()">🖨 Ringkasan YTD/MTD</button><button class="btn secondary" onclick="printDetailReport()">🖨 Detail Penjualan</button></div><h3>Laporan Operasional</h3><div class="actions"><button class="btn secondary" onclick="printRawMaterialPurchaseReport()">🖨 Pembelian Raw Material</button><button class="btn secondary" onclick="printPackagingPurchaseReport()">🖨 Pembelian Packaging</button><button class="btn secondary" onclick="printProductionReport()">🖨 Hasil Produksi</button><button class="btn secondary" onclick="printCostingReport()">🖨 Laporan Costing</button></div><p class="small">Laporan pembelian dan produksi mengikuti filter tanggal Dari–Sampai. Laporan Costing menggunakan data Master Produk saat laporan dicetak.</p></div><div id="reportBody">${reportHtml(currentReport)}</div>`}
window.applyReport=()=>{currentReport=filteredOrders();$('#reportBody').innerHTML=reportHtml(currentReport)}
window.printSummaryReport=()=>{let base=periodBase(),ty=$('#rType')?.value||'ALL',ytd=salesRange(base.yStart,base.ref,ty),mtd=salesRange(base.mStart,base.ref,ty),yt=reportTotals(ytd),mt=reportTotals(mtd),months=monthlySeries(ytd,base.y);printWindow('Ringkasan Penjualan Cemilan Momcip',`<h2>LAPORAN PENJUALAN YTD & MTD</h2><div class="muted">Sampai ${dateID(base.ref)} • Jenis order: ${ty==='ALL'?'Semua':orderTypeLabel(ty)} • Dicetak: ${new Date().toLocaleString('id-ID')}</div><div class="summary"><div class="box"><b>${money(yt.sales)}</b>Penjualan YTD</div><div class="box"><b>${money(yt.profit)}</b>Profit YTD</div><div class="box"><b>${yt.margin.toFixed(1)}%</b>Margin YTD</div><div class="box"><b>${money(mt.sales)}</b>Penjualan MTD</div><div class="box"><b>${money(mt.profit)}</b>Profit MTD</div><div class="box"><b>${mt.margin.toFixed(1)}%</b>Margin MTD</div></div>${summaryTable(`Ringkasan Produk YTD ${base.y}`,ytd)}${customerTable(`Ringkasan Pelanggan YTD ${base.y}`,ytd)}${summaryTable(`Ringkasan Produk MTD ${base.m}/${base.y}`,mtd)}${customerTable(`Ringkasan Pelanggan MTD ${base.m}/${base.y}`,mtd)}<div class="chart-full">${svgLineChart(months,'Trend Penjualan YTD per Bulan')}</div><div class="chart-full">${svgCustomerChart(ytd,'Top Pelanggan YTD berdasarkan Penjualan')}</div>`,'report')}
window.printDetailReport=()=>{let arr=filteredOrders(),ds=dailySummary(arr),t=reportTotals(arr),f=$('#rFrom')?.value||'',to=$('#rTo')?.value||'',ty=$('#rType')?.value||'ALL';printWindow('Detail Penjualan Cemilan Momcip',`<h2>DETAIL LAPORAN PENJUALAN</h2><div class="muted">Periode: ${f?dateID(f):'Awal data'} s.d. ${to?dateID(to):'Akhir data'} • Jenis order: ${ty==='ALL'?'Semua':orderTypeLabel(ty)}</div><div class="summary"><div class="box"><b>${fmt(t.qty)}</b>Qty terjual (Pcs)</div><div class="box"><b>${money(t.sales)}</b>Penjualan</div><div class="box"><b>${money(t.hpp)}</b>HPP</div><div class="box"><b>${money(t.profit)}</b>Profit</div><div class="box"><b>${t.margin.toFixed(1)}%</b>Margin</div></div>${customerTable('Ringkasan per Pelanggan',arr)}<h2>Detail per Tanggal</h2><table class="compact"><thead><tr><th>Tanggal</th><th>Pelanggan</th><th>Produk</th><th class="num">Qty Pcs</th><th class="num">Penjualan</th><th class="num">HPP</th><th class="num">Profit</th><th class="num">Margin</th></tr></thead><tbody>${ds.map(x=>`<tr><td>${dateID(x.date)}</td><td>${esc(x.customer)}</td><td>${esc(x.name)}</td><td class="num">${fmt(x.qty)}</td><td class="num">${money(x.sales)}</td><td class="num">${money(x.hpp)}</td><td class="num">${money(x.profit)}</td><td class="num">${x.sales?(x.profit/x.sales*100).toFixed(1):0}%</td></tr>`).join('')||'<tr><td colspan="8">Belum ada data</td></tr>'}<tr><td colspan="3"><b>TOTAL</b></td><td class="num"><b>${fmt(t.qty)}</b></td><td class="num"><b>${money(t.sales)}</b></td><td class="num"><b>${money(t.hpp)}</b></td><td class="num"><b>${money(t.profit)}</b></td><td class="num"><b>${t.margin.toFixed(1)}%</b></td></tr></tbody></table>`,'report')}
window.printFullReport=window.printSummaryReport
window.printRawMaterialPurchaseReport=()=>{let f=$('#rFrom')?.value||'',to=$('#rTo')?.value||today(),rows=db.materialTx.filter(x=>x.mode==='IN'&&(!f||x.date>=f)&&(!to||x.date<=to)).sort((a,b)=>a.date.localeCompare(b.date)),qty=rows.reduce((s,x)=>s+Number(x.qty||0),0),val=rows.reduce((s,x)=>s+Number(x.qty||0)*Number(x.cost||0),0);let by={};rows.forEach(x=>{let k=x.itemId||x.itemName;if(!by[k])by[k]={name:x.itemName,qty:0,value:0};by[k].qty+=Number(x.qty||0);by[k].value+=Number(x.qty||0)*Number(x.cost||0)});printWindow('Pembelian Raw Material',`<h2>LAPORAN PEMBELIAN RAW MATERIAL</h2><div class="muted">Periode: ${f?dateID(f):'Awal data'} s.d. ${to?dateID(to):'Akhir data'}</div><div class="summary"><div class="box"><b>${rows.length}</b>Transaksi</div><div class="box"><b>${fmt(qty)}</b>Total Qty</div><div class="box"><b>${money(val)}</b>Total Pembelian</div></div><h2>Ringkasan per Material</h2><table class="compact"><thead><tr><th>Material</th><th class="num">Qty</th><th class="num">Nilai</th></tr></thead><tbody>${Object.values(by).map(x=>`<tr><td>${esc(x.name)}</td><td class="num">${fmt(x.qty)}</td><td class="num">${money(x.value)}</td></tr>`).join('')||'<tr><td colspan="3">Belum ada data</td></tr>'}</tbody></table><h2>Detail Pembelian</h2><table class="compact"><thead><tr><th>Tanggal</th><th>Material</th><th class="num">Qty</th><th class="num">Harga/Unit</th><th class="num">Jumlah</th><th>Catatan</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${dateID(x.date)}</td><td>${esc(x.itemName)}</td><td class="num">${fmt(x.qty)}</td><td class="num">${money(x.cost)}</td><td class="num">${money(Number(x.qty||0)*Number(x.cost||0))}</td><td>${esc(x.note||'-')}</td></tr>`).join('')||'<tr><td colspan="6">Belum ada data</td></tr>'}</tbody></table>`,'report')}
window.printPackagingPurchaseReport=()=>{let f=$('#rFrom')?.value||'',to=$('#rTo')?.value||today(),rows=db.packagingTx.filter(x=>x.mode==='IN'&&(!f||x.date>=f)&&(!to||x.date<=to)).sort((a,b)=>a.date.localeCompare(b.date)),qty=rows.reduce((s,x)=>s+Number(x.qty||0),0),val=rows.reduce((s,x)=>s+Number(x.qty||0)*Number(x.cost||0),0);let by={};rows.forEach(x=>{let item=db.packaging.find(p=>p.id===x.itemId),k=x.itemId||x.itemName;if(!by[k])by[k]={name:x.itemName,type:packTypeLabel(item?.type),qty:0,value:0};by[k].qty+=Number(x.qty||0);by[k].value+=Number(x.qty||0)*Number(x.cost||0)});printWindow('Pembelian Packaging',`<h2>LAPORAN PEMBELIAN PACKAGING</h2><div class="muted">Periode: ${f?dateID(f):'Awal data'} s.d. ${to?dateID(to):'Akhir data'}</div><div class="summary"><div class="box"><b>${rows.length}</b>Transaksi</div><div class="box"><b>${fmt(qty)}</b>Total Qty</div><div class="box"><b>${money(val)}</b>Total Pembelian</div></div><h2>Ringkasan per Packaging</h2><table class="compact"><thead><tr><th>Packaging</th><th>Jenis</th><th class="num">Qty</th><th class="num">Nilai</th></tr></thead><tbody>${Object.values(by).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.type)}</td><td class="num">${fmt(x.qty)}</td><td class="num">${money(x.value)}</td></tr>`).join('')||'<tr><td colspan="4">Belum ada data</td></tr>'}</tbody></table><h2>Detail Pembelian</h2><table class="compact"><thead><tr><th>Tanggal</th><th>Packaging</th><th class="num">Qty</th><th class="num">Harga/Unit</th><th class="num">Jumlah</th><th>Catatan</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${dateID(x.date)}</td><td>${esc(x.itemName)}</td><td class="num">${fmt(x.qty)}</td><td class="num">${money(x.cost)}</td><td class="num">${money(Number(x.qty||0)*Number(x.cost||0))}</td><td>${esc(x.note||'-')}</td></tr>`).join('')||'<tr><td colspan="6">Belum ada data</td></tr>'}</tbody></table>`,'report')}
window.printProductionReport=()=>{let f=$('#rFrom')?.value||'',to=$('#rTo')?.value||today(),rows=db.productions.filter(x=>(!f||x.date>=f)&&(!to||x.date<=to)).sort((a,b)=>a.date.localeCompare(b.date)),good=rows.reduce((s,x)=>s+Number(x.qty||0),0),reject=rows.reduce((s,x)=>s+Number(x.reject||0),0),by={};rows.forEach(x=>{let k=x.productId||x.productName;if(!by[k])by[k]={name:x.productName,good:0,reject:0};by[k].good+=Number(x.qty||0);by[k].reject+=Number(x.reject||0)});printWindow('Hasil Produksi',`<h2>LAPORAN HASIL PRODUKSI</h2><div class="muted">Periode: ${f?dateID(f):'Awal data'} s.d. ${to?dateID(to):'Akhir data'}</div><div class="summary"><div class="box"><b>${rows.length}</b>Transaksi</div><div class="box"><b>${fmt(good)}</b>Good</div><div class="box"><b>${fmt(reject)}</b>Reject</div></div><h2>Ringkasan per Produk</h2><table class="compact"><thead><tr><th>Produk</th><th class="num">Good</th><th class="num">Reject</th><th class="num">Total Proses</th></tr></thead><tbody>${Object.values(by).map(x=>`<tr><td>${esc(x.name)}</td><td class="num">${fmt(x.good)}</td><td class="num">${fmt(x.reject)}</td><td class="num">${fmt(x.good+x.reject)}</td></tr>`).join('')||'<tr><td colspan="4">Belum ada data</td></tr>'}</tbody></table><h2>Detail Produksi</h2><table class="compact"><thead><tr><th>Tanggal</th><th>Produk</th><th class="num">Good</th><th class="num">Reject</th><th>Catatan / Batch</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${dateID(x.date)}</td><td>${esc(x.productName)}</td><td class="num">${fmt(x.qty)}</td><td class="num">${fmt(x.reject)}</td><td>${esc(x.note||'-')}</td></tr>`).join('')||'<tr><td colspan="5">Belum ada data</td></tr>'}</tbody></table>`,'report')}


window.printCostingReport=()=>{
 const rows=db.products.map(p=>{
   const pack=Math.max(1,Number(p.packSize||1));
   const hppPcs=Number(p.hpp||0),hppPack=hppPcs*pack;
   const regPcs=Number(p.priceRegular||0),resPcs=Number(p.priceReseller||0);
   const regPack=Number(p.priceRegularPack||0) || regPcs*pack;
   const resPack=Number(p.priceResellerPack||0) || resPcs*pack;
   const regProfitPcs=regPcs-hppPcs,resProfitPcs=resPcs-hppPcs;
   const regProfitPack=regPack-hppPack,resProfitPack=resPack-hppPack;
   return {name:p.name,pack,hppPcs,hppPack,regPcs,resPcs,regPack,resPack,regProfitPcs,resProfitPcs,regProfitPack,resProfitPack,
     regMarginPcs:regPcs?regProfitPcs/regPcs*100:0,resMarginPcs:resPcs?resProfitPcs/resPcs*100:0,
     regMarginPack:regPack?regProfitPack/regPack*100:0,resMarginPack:resPack?resProfitPack/resPack*100:0};
 });
 const avg=(key)=>rows.length?rows.reduce((a,x)=>a+Number(x[key]||0),0)/rows.length:0;
 const body=`<h2>LAPORAN COSTING</h2><div class="muted">Berdasarkan Master Produk • Dicetak: ${new Date().toLocaleString('id-ID')}</div>
 <div class="summary"><div class="box"><b>${rows.length}</b>Total Produk</div><div class="box"><b>${money(avg('hppPcs'))}</b>Rata-rata HPP / Pcs</div><div class="box"><b>${avg('regMarginPcs').toFixed(1)}%</b>Rata-rata Margin Reguler</div></div>
 <h2>Costing Dasar</h2><table class="compact"><thead><tr><th>Produk</th><th class="num">Isi / Pack</th><th class="num">HPP / Pcs</th><th class="num">HPP / Pack</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td class="num">${fmt(x.pack)} Pcs</td><td class="num">${money(x.hppPcs)}</td><td class="num">${money(x.hppPack)}</td></tr>`).join('')||'<tr><td colspan="4">Belum ada produk</td></tr>'}</tbody></table>
 <h2>Harga & Margin per Pcs</h2><table class="compact"><thead><tr><th>Produk</th><th class="num">Harga Reguler</th><th class="num">Profit Reguler</th><th class="num">Margin</th><th class="num">Harga Reseller</th><th class="num">Profit Reseller</th><th class="num">Margin</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td class="num">${money(x.regPcs)}</td><td class="num">${money(x.regProfitPcs)}</td><td class="num">${x.regMarginPcs.toFixed(1)}%</td><td class="num">${money(x.resPcs)}</td><td class="num">${money(x.resProfitPcs)}</td><td class="num">${x.resMarginPcs.toFixed(1)}%</td></tr>`).join('')||'<tr><td colspan="7">Belum ada produk</td></tr>'}</tbody></table>
 <h2>Harga & Margin per Pack</h2><table class="compact"><thead><tr><th>Produk</th><th class="num">Harga Reguler</th><th class="num">Profit Reguler</th><th class="num">Margin</th><th class="num">Harga Reseller</th><th class="num">Profit Reseller</th><th class="num">Margin</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td class="num">${money(x.regPack)}</td><td class="num">${money(x.regProfitPack)}</td><td class="num">${x.regMarginPack.toFixed(1)}%</td><td class="num">${money(x.resPack)}</td><td class="num">${money(x.resProfitPack)}</td><td class="num">${x.resMarginPack.toFixed(1)}%</td></tr>`).join('')||'<tr><td colspan="7">Belum ada produk</td></tr>'}</tbody></table>
 <p class="muted" style="margin-top:12px">Catatan: HPP menggunakan nilai HPP / Pcs pada Master Produk. HPP / Pack = HPP / Pcs × Isi / Pack.</p>`;
 printWindow('Laporan Costing',body,'report');
}

function renderSettings(){
 $('#settings').innerHTML=`<div class="card no-print"><h2>Pengaturan Printer Thermal</h2><div class="row"><div><label>Lebar kertas</label><select id="printWidth"><option value="57" ${getPrintWidth()==='57'?'selected':''}>57 mm</option><option value="75" ${getPrintWidth()==='75'?'selected':''}>75 mm</option><option value="80" ${getPrintWidth()==='80'?'selected':''}>80 mm</option></select></div><div style="display:flex;align-items:end"><button class="btn" style="width:100%" onclick="savePrintWidth()">Simpan Setting Print</button></div></div><p class="small">Dipakai untuk Struk Order dan Outstanding Produksi.</p></div>
 <div class="card"><h2>Master Produk FG</h2><div class="row3 no-print"><input id="mProdName" placeholder="Nama produk"><input id="mProdPack" type="number" min="1" placeholder="Isi / pack (pcs)"><input id="mProdReg" type="number" placeholder="Harga reguler / pcs"><input id="mProdRegPack" type="number" placeholder="Harga reguler / pack"><input id="mProdRes" type="number" placeholder="Harga reseller / pcs"><input id="mProdResPack" type="number" placeholder="Harga reseller / pack"><input id="mProdHpp" type="number" placeholder="HPP / pcs"><input id="mProdMin" type="number" placeholder="Stok minimum (pcs)"><button class="btn" onclick="addMasterProduct()">Tambah Produk</button></div><div class="tablewrap fit"><table><tr><th>Produk</th><th class="num">Isi/Pack</th><th class="num">Reg/Pcs</th><th class="num">Reg/Pack</th><th class="num">Res/Pcs</th><th class="num">Res/Pack</th><th class="num">HPP/Pcs</th><th class="no-print">Aksi</th></tr>${db.products.map(x=>`<tr><td>${esc(x.id)} - ${esc(x.name)}</td><td class="num">${fmt(x.packSize||1)}</td><td class="num">${money(x.priceRegular)}</td><td class="num">${money(x.priceRegularPack)}</td><td class="num">${money(x.priceReseller)}</td><td class="num">${money(x.priceResellerPack)}</td><td class="num">${money(x.hpp)}</td><td class="no-print"><button class="btn secondary smallbtn" onclick="editPackPricing('${x.id}')">Ubah</button> <button class="btn danger smallbtn" onclick="deleteMaster('product','${x.id}')">Delete</button></td></tr>`).join('')}</table></div></div>
 <div class="card"><h2>Master Raw Material</h2><div class="row3 no-print"><input id="mRMName" placeholder="Nama raw material"><input id="mRMUnit" placeholder="Satuan"><input id="mRMMin" type="number" placeholder="Stok minimum"><button class="btn" onclick="addMasterRM()">Tambah RM</button></div><div class="tablewrap fit"><table><tr><th>Kode</th><th>Item</th><th>Satuan</th><th class="num">Min</th><th class="no-print">Aksi</th></tr>${db.materials.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.name)}</td><td>${esc(x.unit)}</td><td class="num">${fmt(x.minStock)}</td><td class="no-print"><button class="btn danger smallbtn" onclick="deleteMaster('material','${x.id}')">Delete</button></td></tr>`).join('')}</table></div></div>
 <div class="card"><h2>Master Packaging</h2><div class="row3 no-print"><input id="mPKName" placeholder="Nama packaging"><select id="mPKType"><option value="INNER">Inner</option><option value="OUTER">Outer</option></select><input id="mPKUnit" placeholder="Satuan"><input id="mPKMin" type="number" placeholder="Stok minimum"><button class="btn" onclick="addMasterPK()">Tambah Packaging</button></div><div class="tablewrap fit"><table><tr><th>Kode</th><th>Item</th><th>Jenis</th><th>Satuan</th><th class="num">Min</th><th class="no-print">Aksi</th></tr>${db.packaging.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.name)}</td><td>${packTypeLabel(x.type)}</td><td>${esc(x.unit)}</td><td class="num">${fmt(x.minStock)}</td><td class="no-print"><button class="btn danger smallbtn" onclick="deleteMaster('packaging','${x.id}')">Delete</button></td></tr>`).join('')}</table></div></div>
 <div class="card no-print"><h2>Backup Data</h2><p class="small">Data tersimpan lokal pada browser/perangkat ini. Backup secara berkala.</p><div class="actions"><button class="btn secondary" onclick="backupData()">Download Backup JSON</button><label class="btn secondary" style="text-align:center">Restore Backup<input id="restoreFile" type="file" accept="application/json" style="display:none" onchange="restoreData(event)"></label><button class="btn danger" onclick="resetData()">Reset Semua Data</button></div></div>`
}
window.savePrintWidth=()=>{localStorage.setItem(PRINTKEY,$('#printWidth').value);alert('Setting printer thermal disimpan: '+$('#printWidth').value+' mm.')}
function nextCode(prefix,arr){let max=arr.reduce((m,x)=>Math.max(m,Number(String(x.id).replace(/\D/g,''))||0),0);return prefix+String(max+1).padStart(3,'0')}
window.addMasterProduct=()=>{let name=$('#mProdName').value.trim();if(!name)return alert('Nama produk wajib diisi.');let id=nextCode('FG',db.products),packSize=Math.max(1,Number($('#mProdPack')?.value)||1),reg=Number($('#mProdReg').value),res=Number($('#mProdRes').value);db.products.push({id,name,unit:'pcs',packSize,priceRegular:reg,priceRegularPack:Number($('#mProdRegPack')?.value)||(reg*packSize),priceReseller:res,priceResellerPack:Number($('#mProdResPack')?.value)||(res*packSize),hpp:Number($('#mProdHpp').value),minStock:Number($('#mProdMin').value)});db.fgStock[id]=0;save()}
window.editPackPricing=id=>{let p=db.products.find(x=>x.id===id);if(!p)return;let ps=prompt('Isi per Pack (Pcs):',p.packSize||1);if(ps===null)return;ps=Math.max(1,Number(ps)||1);let rp=prompt('Harga Reguler / Pack:',p.priceRegularPack||p.priceRegular*ps);if(rp===null)return;let sp=prompt('Harga Reseller / Pack:',p.priceResellerPack||p.priceReseller*ps);if(sp===null)return;p.packSize=ps;p.priceRegularPack=Number(rp)||0;p.priceResellerPack=Number(sp)||0;save()}
window.addMasterRM=()=>{let name=$('#mRMName').value.trim();if(!name)return alert('Nama raw material wajib diisi.');db.materials.push({id:nextCode('RM',db.materials),name,unit:$('#mRMUnit').value||'pcs',stock:0,avgCost:0,minStock:Number($('#mRMMin').value)});save()}
window.addMasterPK=()=>{let name=$('#mPKName').value.trim();if(!name)return alert('Nama packaging wajib diisi.');db.packaging.push({id:nextCode('PK',db.packaging),name,type:$('#mPKType').value,unit:$('#mPKUnit').value||'pcs',stock:0,avgCost:0,minStock:Number($('#mPKMin').value)});save()}
window.deleteMaster=(kind,id)=>{let linked=false,name='';if(kind==='product'){let x=db.products.find(v=>v.id===id);name=x?.name||id;linked=db.orders.some(o=>(o.items||[]).some(i=>i.productId===id))||db.productions.some(p=>p.productId===id)||Number(db.fgStock[id]||0)!==0;if(linked)return alert('Item tidak bisa dihapus karena sudah memiliki transaksi/stock.');if(!confirm(`Delete produk ${name}?`))return;db.products=db.products.filter(x=>x.id!==id);delete db.fgStock[id]}else if(kind==='material'){let x=db.materials.find(v=>v.id===id);name=x?.name||id;linked=db.materialTx.some(t=>t.itemId===id)||Number(x?.stock||0)!==0;if(linked)return alert('Item tidak bisa dihapus karena sudah memiliki transaksi/stock.');if(!confirm(`Delete raw material ${name}?`))return;db.materials=db.materials.filter(x=>x.id!==id)}else{let x=db.packaging.find(v=>v.id===id);name=x?.name||id;linked=db.packagingTx.some(t=>t.itemId===id)||Number(x?.stock||0)!==0;if(linked)return alert('Item tidak bisa dihapus karena sudah memiliki transaksi/stock.');if(!confirm(`Delete packaging ${name}?`))return;db.packaging=db.packaging.filter(x=>x.id!==id)}save()}
window.backupData=()=>{let b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='cemilan-momcip-backup-'+today()+'.json';a.click();URL.revokeObjectURL(a.href)}
window.restoreData=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();alert('Backup berhasil direstore.')}catch(err){alert('File backup tidak valid.')}};r.readAsText(f)}
window.resetData=()=>{if(confirm('Hapus semua data aplikasi? Tindakan ini tidak bisa dibatalkan.')){db=cloneSeed();save()}}

buildNav();render('dashboard');setInterval(()=>{let c=$('#clock');if(c)c.textContent=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})},1000);
